server:
  port: 9050
spring:
  profiles: development
  data:
    mongodb:
      host: srv3.sanjiang.info
      port: 27017
      database: anxian-gateway-admin
  thymeleaf:
      prefix:  file:///F:/JavaProjects/sjes-hub-static/dist/
      suffix: .html
      mode: LEGACYHTML5
      encoding: UTF-8
      content-type: text/html
      cache: false
  resources:
    static-locations:
      - file://${HOME}/sjes/sjes-hub-static/
      - file://${HOME}/sjes/sjes-hub-static/dist/
      - file://${HOME}/sjes/sjes-hub-static/.tmp/

mongeez:
  enabled: false
  location: db/migration/mongeez.xml
security:
  ignored:
    - /favicon.ico
    - /bower_components/**
    - /common/**
    - /scripts/**
    - /images/**
    - /styles/**

picture:
  application:
    address: http://img.dev.sanjiang.info
  upload:
    path: file:///F:/JavaProjects/sjes-hub-static/app/

eureka:
  client:
    serviceUrl:
      defaultZone: http://srv3.sanjiang.info:8761/eureka/
  instance:
    hostname: srv3.sanjiang.info
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000

multipart:
  enabled: true
  max-file-size: 52428800
